#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSl=false
#    username: root
#    password: ""
#    hikari:
#      maximumPoolSize: 10
#
#
#
#
#
#              #JPA settings
#jpa.hibernate.ddl_auto: update
#jpa:
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQLDialect
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#
